# Generated by Django 5.2.4 on 2025-08-08 04:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_employee_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time_in',
            field=models.TimeField(blank=True, null=True, verbose_name='出勤時刻'),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_time', models.TimeField(default=datetime.time(9, 0), verbose_name='開始時刻')),
                ('end_time', models.TimeField(default=datetime.time(18, 0), verbose_name='終了時刻')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='備考')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee', verbose_name='従業員')),
            ],
            options={
                'ordering': ['date', 'employee__code'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
