# Generated by Django 5.2.4 on 2025-08-11 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_time_in_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-date', 'employee__code']},
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='退職や一時停止時にOFF（論理削除）。', verbose_name='在籍'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_in',
            field=models.TimeField(blank=True, null=True, verbose_name='出勤'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_out',
            field=models.TimeField(blank=True, null=True, verbose_name='退勤'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='社員番号'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='時給'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='終了'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='開始'),
        ),
    ]
