# Generated by Django 5.2.4 on 2025-08-05 15:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='社員番号')),
                ('name', models.CharField(max_length=50, verbose_name='氏名')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='勤務日')),
                ('time_in', models.TimeField(verbose_name='出勤時刻')),
                ('time_out', models.TimeField(blank=True, null=True, verbose_name='退勤時刻')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='備考')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee')),
            ],
            options={
                'ordering': ['-work_date', 'employee__code'],
                'unique_together': {('employee', 'work_date')},
            },
        ),
    ]
