# Generated by Django 5.2 on 2025-08-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='時給(円)'),
        ),
    ]
